services:
  registry-system-backend:
    container_name: registry-system-backend
    depends_on:
      - sql
    build:
      dockerfile: Dockerfile
    ports: 
    - "7898:8080"
    
    environment:
      - ConnectionStrings:DefaultConnection=Host=registrySystem-sql:5432;Database=backend;Username=postgres;Password=postgres
  
  sql:
    image: postgres:16
    container_name: registrySystem-sql
    ports:
      # external: internal
      - 5432:5432
    volumes:
      - sql-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: on-failure
    logging:
      options:
        max-size: 10m
        max-file: 3
        
volumes:
  sql-volume: