import Footer from "@/components/Footer"
import { Metadata } from 'next'
import './globals.css';
import NavBar from "@/components/NavBar";


export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-black w-full h-screen border-full flex flex-col">
          <NavBar></NavBar>
          <main className="grow flex-1 w-full h-50 bg-background py-4">{children}</main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  )
}
